export const INIT_CONTACTS = 'INIT_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const ADD_CONTACT_ON_BOARD = 'ADD_CONTACT_ON_BOARD';
export const REMOVE_CONTACT_FROM_BOARD = 'REMOVE_CONTACT_FROM_BOARD';
